spring:
  #  main:
  #    log-startup-info: false

  datasource:
    url: jdbc:mysql://localhost:3306/multi_city_hospital_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true